### ISSUE TITLE
Heavy base image + Sileno mower

### ISSUE THREAD

**Issue by Domochip** [flic/gardena2mqtt-docker#1]
Hi,

I need this kind of docker for my Sileno mower.
I saw that you followed official API guide using the sample WebSocket client. Cool.
I can see 2 things to improve : 
 - base image is heavy, I think it can be adapted to python:3-alpine
 - add Sileno mower

Are you interested about some PR, or you're not anymore active on this and It's better that I create my own repo?

Best regards

**Comment by dobber81** [comment]
@Domochip
Please notify here if you do create a new repo with less heavy image. I would be interested in testing it.

**Comment by Domochip** [comment]
Hi,
Were you able to run it ?
I'm starting to work on this topic and can't run the image in Docker Hub

Traceback (most recent call last):
  File "./gardena2mqtt.py", line 232, in <module>
    main(sys.argv[1:])
  File "./gardena2mqtt.py", line 179, in main
    MQTTPORT = int(arg)
ValueError: invalid literal for int() with base 10: ''

**Comment by dobber81** [comment]
I got it working just fine. What env variables are you sending?

**Comment by Domochip** [comment]
I removed everything and I'm starting a fresh new gardena2mqtt from the official Gardena Python exemple.
(this one is based on too)
I have a Sileno lawnmower.
If you have any other gardena device, Could you please open an issue on my repo with your device name/model to keep in touch.
Then I will be able to ask your help to implement and make some tests/validations :-)

https://github.com/Domochip/gardena2mqtt
